# Generated by Django 3.1.3 on 2020-11-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shape_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='size_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='topping_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pizza_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.shape_pizza')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.size_pizza')),
                ('topping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.topping_type')),
            ],
        ),
    ]
