# Generated by Django 3.1.3 on 2020-11-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='piza_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='shape_piza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='size_piza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='pizza_type',
        ),
        migrations.DeleteModel(
            name='shape_pizza',
        ),
        migrations.DeleteModel(
            name='size_pizza',
        ),
        migrations.DeleteModel(
            name='topping_type',
        ),
        migrations.AddField(
            model_name='piza_type',
            name='shape_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.shape_piza'),
        ),
        migrations.AddField(
            model_name='piza_type',
            name='size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.size_piza'),
        ),
    ]
