# Generated by Django 3.1.3 on 2020-11-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_api', '0002_auto_20201125_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='piza_type',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_api.choice'),
            preserve_default=False,
        ),
    ]
